### ISSUE TITLE
ID Station Field Not Accepting Alphanumeric

### ISSUE THREAD

**Issue by scurvy-dog** [itemir/signalk-windy#1]
The windy plugin for signalk looks to only accept integer values on the plugin setup screen. Created Windy.com station this week and it kicks out an 8 digit alphanumeric value. Can you update the station id to take in string value now instead of integer.

**Comment by itemir** [comment]
Are you sure about this? There are two fields, one is _ID_ that is a hex value, something like "ae07d24ca". The other is _Station ID_ which is a numerical value. It is the latter that you need to use, not the former.

**Comment by itemir** [comment]
Closing this, re-open if above comment doesn't address it.
