### ISSUE TITLE
humidity not sent

### ISSUE THREAD

**Issue by dirkwa** [itemir/signalk-windy#10]
In my databrowser I have environment.outside.humidity
value: -0.00508
Units: Ratio

In the transmission is only:
Sep 23 13:57:57 2024-09-23T01:57:57.792Z signalk-windy Submitting data: {"stations":[{"station":0,"name":"MOIN","shareOption":"Open","type":"Signal K Windy Plugin","provider":"SV MOIN","url":"","lat":-17.1882216,"lon":-179.0001815,"elevation":1}],"observations":[{"station":0,"temp":29.5,"wind":0.05,"gust":1.58,"winddir":288,"pressure":101498,"rh":null}]}

**Comment by itemir** [comment]
Humidity cannot be a negative value. What is the source of that reading?

**Comment by dirkwa** [comment]
Thanks for your quick reply. 
NGT1.47  (130311)

**Comment by itemir** [comment]
You should trace it down. Negative humidity doesn't make sense and is not a correct reading.

**Comment by dirkwa** [comment]
I found it. I have 2 sensors filling it. The other one has 130313 with the correct value. 
I added in Data Source a priority for this one. Now it works. Case can be closed, thanks a lot!
