### ISSUE TITLE
feature request: add wind gust

### ISSUE THREAD

**Issue by MichelleWhy** [itemir/signalk-windy#3]
Thanks for the plugin!
I'd love to see wind `gust` reporting to  windy.com

Not sure how this is possible within Signal K as this item is nowhere in the path list and not reported by my Raymarine wind sensor. Maybe by collecting wind data for a specific time frame, then report the average as `wind `and the highest number as `gust` ?

**Comment by itemir** [comment]
Thanks for the interest Michelle. This is addressed in the new release (1.0.0) I just published. You can see a sample [here](https://www.windy.com/station/pws-f06d21ca).
